// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgrlcsimdszbrkcwjpke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtncmxjc2ltZHN6YnJrY3dqcGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDc0MTgsImV4cCI6MjA2NTQyMzQxOH0.dvfwgMT1_Ru6EOlPalkPb94KmwoU1dcCLKcSBJBQML0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);